services:
  dbt-server:
    extends:
      file: docker-compose.base.yml
      service: dbt-server-base
    cpus: 32
    mem_limit: 120g
    volumes:
      - ./mount/raw/${SCALE_FACTOR:-3}/delta:/data/raw/delta:ro
      - ./mount/results/${SCALE_FACTOR:-3}/duckdb:/data/processed/duckdb
      - ./mount/stats/${SCALE_FACTOR:-3}/duckdb:/data/stats
