services:
  spark-batch-loader:
    build:
      context: ./src/containers/spark-batch-loader
      args:
        SBT_IMAGE: "sbtscala/scala-sbt:eclipse-temurin-17.0.15_6_1.12.6_2.12.21"
        SPARK_VERSION: "3.5.8"
        SCALA_VERSION: "2.12.18"
        DELTA_VERSION: "3.3.2"
        HADOOP_VERSION: "3.3.4"
    cpus: ${BATCH_LOADER_CPUS:-32}
    mem_limit: ${BATCH_LOADER_MEM:-128g}
    volumes:
      - ./mount/raw/${SCALE_FACTOR:-3}/delta:/data/delta
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xmx${BATCH_LOADER_HEAP:-80g} -Xms${BATCH_LOADER_HEAP:-80g} -XX:G1HeapRegionSize=16m -XX:ParallelGCThreads=${BATCH_LOADER_GC_THREADS:-16} -XX:ConcGCThreads=${BATCH_LOADER_CONC_GC_THREADS:-8} -XX:+UseNUMA -XX:+AlwaysPreTouch"
      DELTA_PATH: /data/delta
