name: 'tpcdi'
version: '1.0.0'
config-version: 2

profile: 'tpcdi'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["tpcdi", "dbt_utils"]

on-run-start:
  - "{{ register_tpcdi_sources() }}"

models:
  tpcdi:
    bronze:
      +schema: bronze
      +materialized: table
      +file_format: delta
      +location_root: "none"
    silver:
      +schema: silver
      +materialized: table
      +file_format: delta
      +location_root: "none"
    gold:
      +schema: gold
      +materialized: table
      +file_format: delta
      +location_root: "none"
    work:
      +schema: work
      +materialized: ephemeral
