tpcdi:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: ':memory:'
      database: ducklake
      threads: 1
      config_options:
        allow_unsigned_extensions: true
      settings:
        preserve_insertion_order: false
        memory_limit: "{{ env_var('DUCKDB_MEM_LIMIT', '115GB') }}"
        threads: "{{ env_var('DUCKDB_THREADS', '32') | int }}"
        temp_directory: "{{ env_var('DUCKDB_TEMP_DIR', '/data/processed/duckdb/_tmp') }}"
      extensions:
        - parquet
        - sqlite
        - ducklake
      attach:
        - path: "ducklake:sqlite:/data/processed/duckdb/metadata.db"
          alias: ducklake
          options:
            data_path: /data/processed/duckdb/data
            data_inlining_row_limit: 0
