-- Nested ROW types match the actual Delta/Parquet schema from spark-xml
_ActionTS TIMESTAMP NULL,
_ActionType VARCHAR NULL,
Customer ROW(
  Account ROW(
    CA_B_ID BIGINT NULL,
    CA_NAME VARCHAR NULL,
    _CA_ID BIGINT NULL,
    _CA_TAX_ST BIGINT NULL,
    _VALUE VARCHAR NULL
  ) NULL,
  Address ROW(
    C_ADLINE1 VARCHAR NULL,
    C_ADLINE2 VARCHAR NULL,
    C_CITY VARCHAR NULL,
    C_CTRY VARCHAR NULL,
    C_STATE_PROV VARCHAR NULL,
    C_ZIPCODE VARCHAR NULL
  ) NULL,
  ContactInfo ROW(
    C_ALT_EMAIL VARCHAR NULL,
    C_PHONE_1 ROW(C_AREA_CODE BIGINT NULL, C_CTRY_CODE BIGINT NULL, C_EXT BIGINT NULL, C_LOCAL VARCHAR NULL) NULL,
    C_PHONE_2 ROW(C_AREA_CODE BIGINT NULL, C_CTRY_CODE BIGINT NULL, C_EXT BIGINT NULL, C_LOCAL VARCHAR NULL) NULL,
    C_PHONE_3 ROW(C_AREA_CODE BIGINT NULL, C_CTRY_CODE BIGINT NULL, C_EXT BIGINT NULL, C_LOCAL VARCHAR NULL) NULL,
    C_PRIM_EMAIL VARCHAR NULL
  ) NULL,
  Name ROW(
    C_F_NAME VARCHAR NULL,
    C_L_NAME VARCHAR NULL,
    C_M_NAME VARCHAR NULL
  ) NULL,
  TaxInfo ROW(
    C_LCL_TX_ID VARCHAR NULL,
    C_NAT_TX_ID VARCHAR NULL
  ) NULL,
  _C_DOB DATE NULL,
  _C_GNDR VARCHAR NULL,
  _C_ID BIGINT NULL,
  _C_TAX_ID VARCHAR NULL,
  _C_TIER BIGINT NULL,
  _VALUE VARCHAR NULL
) NULL
