tpcdi:
  target: feldera
  outputs:
    feldera:
      type: feldera
      host: "{{ env_var('FELDERA_URL', 'http://pipeline-manager:8080') }}"
      database: "default"
      schema: "tpcdi"
      compilation_profile: optimized
      workers: 12
      timeout: 1200
      threads: 1
      max_rss_mb: "{{ env_var('FELDERA_MAX_RSS_MB', '0') | int }}"
      dev_tweaks:
        adaptive_joins: true
