tpcdi:
  target: feldera
  outputs:
    feldera:
      type: feldera
      host: "{{ env_var('FELDERA_URL', 'http://pipeline-manager:8080') }}"
      database: "default"
      schema: "tpcdi"
      compilation_profile: optimized
      workers: 16
      timeout: 1200
      threads: 1
